[tool.poetry]
name = "qctrl-qiskit"
version = "0.0.3"
description = "Q-CTRL Qiskit Adapter"
license = "Apache-2.0"
authors = ["Q-CTRL <support@q-ctrl.com>"]
readme = "README.md"
keywords = [
    "quantum", 
    "computing", 
    "open source", 
    "engineering",
    "qiskit"
]
classifiers = [
            "Development Status :: 5 - Production/Stable",
            "Environment :: Console",
            "Intended Audience :: Developers",
            "Intended Audience :: Education",
            "Intended Audience :: Science/Research",
            "License :: OSI Approved :: Apache Software License",
            "Natural Language :: English",
            "Operating System :: OS Independent",
            "Programming Language :: Python :: 3.6",
            "Topic :: Scientific/Engineering :: Physics",
            "Topic :: Scientific/Engineering :: Visualization",
            "Topic :: Software Development :: Embedded Systems",
            "Topic :: System :: Distributed Computing"
        ]
repository = "https://github.com/qctrl/python-qiskit"
packages = [
    { include = "qctrlqiskit" },
]

[tool.poetry.dependencies]  # https://poetry.eustace.io/docs/versions
python = ">=3.6.4,<3.8"
numpy = "^1.16"
scipy = "^1.3"
toml = "^0.10.0"
qiskit-ibmq-provider = "^0.3.3"
qiskit-terra = "^0.10.0"
qctrl-open-controls = "^3.0.0"


[tool.poetry.dev-dependencies]
pytest = "*"
pylama = "*"
pylint = "*"
pylint_runner = "*"
sphinx = "^2.2.0"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
versioning = "pep"
prereleases = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

#  _______________________________________
# / If you update this file, please run   \
# \ poetry update && dephell deps convert /
#  ---------------------------------------
#        \   ^__^
#         \  (oo)\_______
#            (__)\       )\/\
#                ||----w |
#                ||     ||

